package domain

import (
	"errors"
	"time"
)

// Sentinel error stok opname.
var (
	ErrOpnameTidakDitemukan   = errors.New("stok opname tidak ditemukan")
	ErrOpnameStatusInvalid    = errors.New("status opname tidak valid")
	ErrOpnameTransitionInvalid = errors.New("transisi status opname tidak diizinkan")
	ErrOpnameItemTidakDitemukan = errors.New("item opname tidak ditemukan")
	ErrOpnameQtyFisikInvalid  = errors.New("qty fisik tidak valid")
	ErrOpnameGudangWajib      = errors.New("gudang wajib diisi untuk opname")
)

// StatusOpname enum status stok opname.
type StatusOpname string

const (
	OpnameDraft    StatusOpname = "draft"
	OpnameSelesai  StatusOpname = "selesai"
	OpnameApproved StatusOpname = "approved"
)

// IsValid cek nilai status opname.
func (s StatusOpname) IsValid() bool {
	switch s {
	case OpnameDraft, OpnameSelesai, OpnameApproved:
		return true
	}
	return false
}

// CanTransitionTo cek apakah transisi status valid.
func (s StatusOpname) CanTransitionTo(next StatusOpname) bool {
	switch s {
	case OpnameDraft:
		return next == OpnameSelesai
	case OpnameSelesai:
		return next == OpnameApproved
	}
	return false
}

// StokOpname header stok opname.
type StokOpname struct {
	ID         int64
	Nomor      string
	GudangID   int64
	GudangNama string // hydrate-only
	Tanggal    time.Time
	UserID     int64
	UserNama   string // hydrate-only
	Status     StatusOpname
	Catatan    string
	Items      []StokOpnameItem
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Validate header opname.
func (o *StokOpname) Validate() error {
	if o.GudangID <= 0 {
		return ErrOpnameGudangWajib
	}
	if !o.Status.IsValid() {
		return ErrOpnameStatusInvalid
	}
	return nil
}

// StokOpnameItem baris item opname.
type StokOpnameItem struct {
	ID         int64
	OpnameID   int64
	ProdukID   int64
	ProdukNama string
	QtySistem  float64
	QtyFisik   float64
	Selisih    float64 // generated by DB
	Keterangan string
}
